"""Blocklist of disposable / throwaway email providers.

Usage:
    from disposable_domains import is_disposable_email
    if is_disposable_email("user@mailinator.com"):
        # reject
"""
from __future__ import annotations

_DOMAINS: frozenset[str] = frozenset({
    "10minutemail.com", "10minutemail.net", "10minutemail.org",
    "10minutemail.co.uk", "10minutemail.de", "10minutemail.ru",
    "10minemail.com", "20minutemail.com", "33mail.com",
    "altmails.com", "anonymbox.com", "antichef.com", "antichef.net",
    "armyspy.com", "avemail.com",
    "beefmilk.com", "binkmail.com", "bio-muesli.info",
    "bobmail.info", "bofthew.com", "boxtemp.com.br",
    "boximail.com", "bumpymail.com", "bund.us",
    "byom.de",
    "cardinalpoint.net", "casualdx.com", "cek.pm",
    "centermail.com", "centermail.net", "chogmail.com",
    "chong-mail.net", "chotmail.com", "clrmail.com",
    "cmail.net", "col.la", "correo.blogos.net",
    "cosmorph.com", "courrieltemporaire.com", "cubiclink.com",
    "curryworld.de", "cust.in",
    "dacoolest.com", "daemsteam.com", "dandikmail.com",
    "dayrep.com", "dcemail.com", "deadaddress.com",
    "deadletter.ga", "deagot.com", "dealja.com",
    "despam.it", "despammed.com", "devnullmail.com",
    "dfgh.net", "digitalsanctuary.com", "dingbone.com",
    "discardmail.com", "discardmail.de", "discard.email",
    "dispostable.com", "dodgeit.com", "dodgit.com",
    "donemail.ru", "dontsendmespam.de", "dotman.de",
    "drdrb.com", "drdrb.net", "dsiay.com",
    "dump-email.info", "dumpandfuck.com", "dumpmail.de",
    "dumpyemail.com", "durandinterstellar.com",
    "e-mail.com", "e4ward.com", "easytrashmail.com",
    "elwet.com", "email-fake.com", "emailgo.de",
    "emailias.com", "emailinfive.com", "emailisvalid.com",
    "emailmiser.com", "emailnax.com", "emailondeck.com",
    "emailsensei.com", "emailtemporario.com.br", "emailto.de",
    "emailwarden.com", "emailx.at.hm", "emailxfer.com",
    "emkei.cz", "emkei.ga", "emkei.gq", "emkei.ml", "emkei.tk",
    "enterto.com", "ephemail.net", "etranquil.com",
    "ezfill.com", "ezstest.com",
    "fakeinbox.com", "fakeinbox.net", "fakeinbox.org",
    "fakeinformation.com", "fakemail.fr",
    "fakemailgenerator.com", "fammix.com", "fanclub.pm",
    "fantasymail.de", "fast-email.com", "fast-mail.fr",
    "fastem.com", "fastemail.us", "fastemailer.com",
    "fastemails.us", "fastermail.com", "fastest.cc",
    "fatflap.com", "fdcserver.net", "fightallspam.com",
    "filzmail.com", "flyspam.com", "footard.com",
    "forgetmail.com", "forward.cat", "fr33mail.info",
    "frapmail.com", "freundin.ru",
    "fudgerub.com", "fux0ringduh.com",
    "garliclife.com", "get1mail.com", "get2mail.fr",
    "getairmail.com", "getmails.eu", "getonemail.com",
    "getonemail.net", "ghosttexter.de", "girlsindetention.com",
    "gishpuppy.com", "glitch.sx", "goemailgo.com",
    "gotmail.net", "gotmail.org", "grr.la",
    "gsrv.co.uk", "guerillamail.biz", "guerillamail.com",
    "guerillamail.de", "guerillamail.info", "guerillamail.net",
    "guerillamail.org", "guerillamailblock.com", "guerrillamail.biz",
    "guerrillamail.com", "guerrillamail.de", "guerrillamail.info",
    "guerrillamail.net", "guerrillamail.org", "guerrillamailblock.com",
    "gustr.com",
    "h8s.org", "haltospam.com", "haqed.com",
    "hat-geld.de", "hatespam.org", "herp.in",
    "hidemail.de", "high.cz", "hidzz.com",
    "hmamail.com", "hopemail.biz", "horsef*cker.com",
    "hulapla.de",
    "ieatspam.eu", "ieatspam.info", "ieh-mail.de",
    "ignoremail.com", "ihateyoualot.info", "iheartspam.org",
    "imap.cc", "imails.info", "imgof.com",
    "imstations.com", "inbax.tk", "inbox.si",
    "inboxclean.com", "inboxclean.org", "inoutmail.de",
    "inoutmail.eu", "inoutmail.info", "inoutmail.net",
    "insorg-mail.info", "instant-mail.de", "internet-e-mail.de",
    "internet-mail.de", "internet4ever.com", "internetemails.net",
    "internetmailing.net", "intrazone.com", "invalid.com",
    "ipoo.org", "irish2me.com", "jetable.com",
    "jetable.fr.nf", "jetable.net", "jetable.org",
    "jnxjn.com", "jojomail.com", "junk1.com",
    "junkmail.com", "junkmail.ga", "junkmail.gq",
    "kasmail.com", "kaspop.com", "killmail.com",
    "killmail.net", "klzlk.com", "koszmail.pl",
    "kurzepost.de", "lackmail.net", "laste.ml",
    "letthemeatspam.com", "lhsdv.com", "lifebyfood.com",
    "link2mail.net", "litedrop.com", "lol.ovpn.to",
    "lovemeleaveme.com", "ltda.de", "lukemail.com",
    "lyricspad.net",
    "m4ilweb.info", "maboard.com", "mail-filter.com",
    "mail-temporaire.fr", "mail.by", "mail.mezimages.net",
    "mail1a.de", "mail21.cc", "mail2rss.org",
    "mail333.com", "mail4trash.com", "mailbidon.com",
    "mailbiz.biz", "mailblocks.com", "mailbolt.com",
    "mailc.net", "mailcat.biz", "mailcatch.com",
    "maildrop.cc", "maildrop.cf", "maildrop.ga",
    "maildrop.gq", "maildrop.ml", "mailexpire.com",
    "mailf5.com", "mailfall.com", "mailfree.ga",
    "mailfreeonline.com", "mailguard.me", "mailhazard.com",
    "mailimate.com", "mailin8r.com", "mailinater.com",
    "mailinator.com", "mailinator.net", "mailinator.org",
    "mailinator2.com", "mailinator2.net", "mailincubator.com",
    "mailismagic.com", "mailita.tk", "mailjunk.cf",
    "mailjunk.ga", "mailjunk.gq", "mailjunk.ml",
    "mailjunk.tk", "mailme.gq", "mailme.ir",
    "mailme.lv", "mailme24.com", "mailmetrash.com",
    "mailnew.com", "mailnull.com", "mailorg.org",
    "mailpluss.com", "mailproxsy.com", "mailquack.com",
    "mailrock.biz", "mailscrap.com", "mailshell.com",
    "mailsiphon.com", "mailslapping.com", "mailslite.com",
    "mailsurfer.cc", "mailtemp.info", "mailtemporaire.fr",
    "mailthink.net", "mailtrash.net", "mailtrix.net",
    "mailtv.net", "mailzilla.com", "mailzilla.org",
    "makemetheking.com", "manifestgeno.com", "mankyrecords.com",
    "mbx.cc", "meltmail.com", "messagebeamer.de",
    "mezimages.net", "mierdamail.com", "mintemail.com",
    "moburl.com", "moncourrier.fr.nf", "monemail.fr.nf",
    "monmail.fr.nf", "monumentmail.com", "msamail.com",
    "mt2009.com", "mt2014.com", "munouburo.com",
    "mycard.net.ua", "mycleaninbox.net", "mymail-in.net",
    "mymailoasis.com", "mynetstore.de", "myspamless.com",
    "mytemp.email", "mytempemail.com", "mytempmail.net",
    "myvnc.com",
    "nafko.cf", "netzidiot.de", "neverbox.com",
    "nice-4u.com", "nigge.rs", "nmail.cf",
    "noblepioneer.com", "no-spam.ws", "nobulk.com",
    "noclickemail.com", "nogmailspam.info", "nospam.ze.tc",
    "nospam4.us", "nospamfor.us", "nospammail.net",
    "nospamthanks.info", "notmailinator.com", "notsharingmy.info",
    "nowhere.org", "nowmymail.com", "nurfuerspam.de",
    "objectmail.com", "obobbo.com", "odaymail.com",
    "odnorazovoe.ru", "oneoffemail.com", "onewaymail.com",
    "online.ms", "onqin.com", "opentrash.com",
    "ordinaryamerican.net", "otherinbox.com", "ourklips.com",
    "ourpreviewdomain.com", "outlawspam.com", "ovpn.to",
    "owlpic.com",
    "pancakemail.com", "paplease.com", "pc1.cz",
    "pepbot.com", "pfui.ru", "pimpedupmyspace.com",
    "pjjkp.com", "plexolan.de", "plusplusplus.cz",
    "poczta.onet.pl", "politikerclub.de", "pookmail.com",
    "postalmail.biz", "privacy.net", "privatdemail.net",
    "proxymail.eu", "prtnx.com", "punkass.com",
    "putthisinyourspamdatabase.com",
    "qq.com",
    "raketenmann.de", "rcpt.at", "recode.me",
    "recursor.net", "recyclemail.dk", "regbypass.com",
    "regbypass.comsafe-mail.net", "rejectmail.com",
    "reliable-mail.com", "renta.com", "rhyta.com",
    "rklips.com", "rmqkr.net", "royal.net",
    "rtrtr.com",
    "s0ny.net", "safe-mail.net", "safetymail.info",
    "safetypost.de", "sandelf.de", "sast.ro",
    "scatmail.com", "schafmail.de", "schrott-email.de",
    "secretemail.de", "secure-mail.biz", "sendspamhere.com",
    "sharklasers.com", "shiftmail.com", "shitmail.me",
    "shitware.nl", "siesmail.com", "signalwriter.com",
    "sinmail.dk", "skeefmail.com", "slapsfromlastnight.com",
    "slaskpost.se", "slipry.net", "slo.net",
    "slopsbox.com", "slushmail.com", "smashmail.de",
    "smellfear.com", "snakemail.com", "sneakemail.com",
    "sneakmail.de", "sniggits.com", "sofimail.com",
    "sofort-mail.de", "sogetthis.com", "sohai.ml",
    "spam.la", "spam.su", "spam4.me",
    "spamavert.com", "spambob.com", "spambob.net",
    "spambob.org", "spambog.com", "spambog.de",
    "spambog.ru", "spambox.info", "spambox.irishspringrealty.com",
    "spambox.us", "spamcannon.com", "spamcannon.net",
    "spamcero.com", "spamcon.org", "spamcorptastic.com",
    "spamcowboy.com", "spamcowboy.net", "spamcowboy.org",
    "spamday.com", "spamex.com", "spamfree.eu",
    "spamfree24.de", "spamfree24.eu", "spamfree24.info",
    "spamfree24.net", "spamfree24.org", "spamgoes.in",
    "spamgourmet.com", "spamgourmet.net", "spamgourmet.org",
    "spamherelots.com", "spamherelots.com", "spamhereplease.com",
    "spamhole.com", "spamify.com", "spaminator.de",
    "spamkill.info", "spaml.com", "spaml.de",
    "spammotel.com", "spammy.host", "spamoff.de",
    "spamslicer.com", "spamspot.com", "spamthis.co.uk",
    "spamthisplease.com", "spamtrail.com", "spamtroll.net",
    "speed.1s.fr", "splymail.com", "spoofmail.de",
    "squizzy.de", "squizzy.eu", "squizzy.net",
    "storagemailbox.com", "stuffmail.de", "super-auswahl.de",
    "supergreatmail.com", "supermailer.jp", "superrito.com",
    "suremail.info",
    "tafmail.com", "tagyourself.com", "talkinator.com",
    "teewars.org", "teleworm.com", "teleworm.us",
    "temp-mail.com", "temp-mail.de", "temp-mail.org",
    "temp-mail.ru", "temp-mail.io", "temp.emeraldwebmail.com",
    "tempalias.com", "tempail.com", "tempemail.biz",
    "tempemail.com", "tempemail.net", "tempimbox.com",
    "tempinbox.co.uk", "tempinbox.com", "tempm.com",
    "tempmail.de", "tempmail.eu", "tempmail.it",
    "tempmail.net", "tempmail.org", "tempmail.us",
    "tempmail2.com", "tempmailaddress.com", "tempmailer.de",
    "tempmailer.net", "tempmails.org", "tempor.email",
    "temporarioemail.com.br", "temporaryemail.net", "temporaryemail.us",
    "temporaryforwarding.com", "temporaryinbox.com", "temporarymailaddress.com",
    "thanksnospam.info", "thc.st", "thelimestones.com",
    "thisisnotmyrealemail.com", "throwam.com", "throwaway.email",
    "throwam.com", "throwit.email", "throwit.net",
    "tilien.com", "tmailinator.com", "toiea.com",
    "toomail.biz", "topranklist.de", "tradermail.info",
    "trash-amil.com", "trash-mail.at", "trash-mail.com",
    "trash-mail.de", "trash-mail.ga", "trash-mail.io",
    "trash-mail.net", "trash2009.com", "trash2010.com",
    "trash2011.com", "trashdevil.com", "trashemail.de",
    "trashmail.at", "trashmail.com", "trashmail.de",
    "trashmail.io", "trashmail.me", "trashmail.net",
    "trashmail.org", "trashmail.se", "trashmailer.com",
    "trashme.fr", "trashmails.com", "trashymail.com",
    "tradermail.info", "turual.com", "twinmail.de",
    "twoweirdtricks.com",
    "uggsrock.com", "umail.net", "unids.com",
    "uroid.com", "uses.info", "utiket.us",
    "veryrealemail.com", "viditag.com", "viewcastmedia.com",
    "viewcastmedia.net", "viewcastmedia.org", "vomoto.com",
    "voxelcore.com",
    "walala.org", "walkmail.net", "walkmail.ru",
    "wam.co.za", "webemail.me", "webm4il.info",
    "weg-werf-email.de", "wegwerf-email.at", "wegwerf-email.de",
    "wegwerf-email.net", "wegwerfadresse.de", "wegwerfemail.com",
    "wegwerfemail.de", "wegwerfemail.info", "wegwerfemail.net",
    "wegwerfmail.de", "wegwerfmail.info", "wegwerfmail.net",
    "wegwerfmail.org", "wereweb.me", "wh4f.org",
    "whyspam.me", "willhackforfood.biz", "wilemail.com",
    "willselfdestruct.com", "winemaven.info", "wronghead.com",
    "ws.gy", "wwwnew.eu",
    "xagloo.co", "xagloo.com", "xemaps.com",
    "xents.com", "xmaily.com", "xoxy.net",
    "xyzzy.tk", "xyzfree.net",
    "yapped.net", "yep.it", "yes-am.com",
    "yobt.tv", "yopmail.com", "yopmail.fr",
    "yopmail.net", "yopmail.org", "yopmail.pp.ua",
    "you-spam.com", "yourdomain.com", "ypmail.webarnak.fr.eu.org",
    "yuurok.com",
    "z1p.biz", "za.com", "zehnminutenmail.de",
    "zetmail.com", "zippymail.info", "zoemail.net",
    "zoemail.org", "zomg.info", "zombo.com",
})

_COMMON_LEGIT_DOMAINS: frozenset[str] = frozenset({
    "gmail.com", "yahoo.com", "outlook.com", "hotmail.com",
    "live.com", "icloud.com", "me.com", "mac.com",
    "aol.com", "protonmail.com", "proton.me", "pm.me",
    "fastmail.com", "hey.com", "tutanota.com", "zoho.com",
    "msn.com", "comcast.net", "att.net", "verizon.net",
    "sbcglobal.net", "bellsouth.net", "cox.net", "charter.net",
    "earthlink.net", "optonline.net", "bigpond.com", "bigpond.net.au",
    "mail.com", "email.com", "usa.com", "techie.com",
})


def is_disposable_email(email: str) -> bool:
    """Return True if the email address uses a known disposable domain."""
    email = email.strip().lower()
    if "@" not in email:
        return False
    domain = email.rsplit("@", 1)[1]
    return domain in _DOMAINS


def get_domain(email: str) -> str:
    email = email.strip().lower()
    if "@" not in email:
        return ""
    return email.rsplit("@", 1)[1]
