uploads = []

[[generated]]
id = "RAN3v0n6mKOc6giraXDQA"
uri = "file://static/images/hero-cinematic.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "rnr2d5_9L3t730VXE8PRz"
uri = "file://static/qaivid_kickstarter_campaign.pdf"
type = "pdf"
title = "Qaivid Kickstarter Campaign — Both Versions"

[[outputs]]
id = "IIuIkxbqkRmTkVboHKLZI"
uri = "file://stills_page_files.zip"
type = "unspecified"
title = "Stills Page Source Files"

[[outputs]]
id = "M47q4mJCgiHsBlaKk9HyV"
uri = "file://postprod_design_files.zip"
type = "unspecified"
title = "Post Production Design Files"
